repositoryUrl: https://github.com/Dynamsoft/label-recognition/blob/master

docHomePage: /label-recognition

programming: /label-recognition/programming/

c: /label-recognition/programming/c/
cpp: /label-recognition/programming/cplusplus/